version: '3.8'

services:

  nginx:
    depends_on:
      - backend
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'

  postgres:
    image: 'postgres:latest'
    env_file:
      - ./.env
    ports: 
      - '7000:5432'

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    depends_on:
      - postgres
    volumes:
      - ./server/src:/app/src:ro
    env_file:
      - ./.env
    ports:
      - '5000:5000'

  client:
    build:
      dockerfile: Dockerfile.dev
      context: './client'
    volumes:
      - ./client/src:/app/src:ro
    env_file:
      - ./.env
    ports:
      - '3000:3000'
