version: '3.8'

services:

  postgres:
    image: 'postgres:latest'
    env_file:
      - ./dev.env

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./dev.env
    ports:
      - '5050:80'
    depends_on:
      - postgres

    #------------------------------------------------------------------------
    # Original author: matschik
    # Repository: https://github.com/matschik/docker-compose-postgres-pgadmin
    user: root
    volumes:
      - ./pgAdmin/entrypoint.sh:/entrypoint_custom.sh
    entrypoint: /entrypoint_custom.sh
    #------------------------------------------------------------------------

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    depends_on:
      - postgres
    volumes:
      - ./server/src:/app/src:ro
    env_file:
      - ./dev.env
    ports:
      - '5000:5000'

  client:
    build:
      dockerfile: Dockerfile.dev
      context: './client'
    volumes:
      - ./client/src:/app/src:ro
    env_file:
      - ./dev.env
    ports:
      - '3000:3000'
