name: pipeline
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
    
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
    
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push client
        id: build-push-client
        uses: docker/build-push-action@v3
        with:
          context: ./client
          file: Dockerfile.prod
          push: true
          tags: logiverum/organizer:client

      - name: build and push backend
        id: build-push-backend
        uses: docker/build-push-action@v3
        with:
          context: ./server
          file: Dockerfile.prod
          push: true
          tags: logiverum/organizer:server